Create Flatpak manifest
elementary/screenshot pull request #162
Opened 2020-06-24 00:34 UTC by danrabbit

Fails to run due to problem with Settings

2020-06-24 02:06 UTC, Marukesu commented
maybe because the baseapp doesn't install the defaults-settings, so it don't have AccountsServices in the sandbox? the same apply to the elementary sdk

2020-06-24 02:08 UTC, Marukesu commented
also, it's need the `rename-icon` tag

2020-08-06 08:08 UTC, Marukesu commented
adding `--system-talk-name=org.freedesktop.Accounts` and `--talk-name=org.gnome.Shell.Screenshot` make it run, but conceal won't work.

2020-10-20 22:20 UTC, danrabbit commented
Hey @Marukesu thanks for the review! The icon issue should be resolved and conceal is now done over the dbus interface. I'm stilling having an issue running though:

`Failed to register: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown`

Any ideas?

2020-10-20 23:16 UTC, bilelmoussaoui commented on io.elementary.screenshot.yml
> +base-version: juno-19.08
There's a 20.08 version based on fdo 20.08/ gnome 3.38

2020-10-21 18:40 UTC, Marukesu commented
The error is the flatpak app-id (`io.elementary.screenshot`) don't match the app name (`io.elementary.screenshot-tool`), neither the gsettings schema (so it don't migrate the app settings), the solution is keep the app-id to `io.elementary.screenshot-tool` until #178 is merged. Also, the manifest need to add `--filesystem=home` and `--socket=pulseaudio` for save, conceal and sound.

2020-10-23 09:05 UTC, fabiozaramella commented
#178 has just been merged so you may want to update this PR once again 😅

2020-10-23 18:47 UTC, danrabbit commented
@fabiozaramella updated!

2020-11-03 18:18 UTC, Marukesu requested changes
some minor changes.

2020-11-03 18:18 UTC, Marukesu commented on .github/workflows/main.yml
> +    - uses: bilelmoussaoui/flatpak-github-actions@v1
```suggestion
    - uses: bilelmoussaoui/flatpak-github-actions@v2
```

2020-11-03 18:18 UTC, Marukesu commented on io.elementary.screenshot.yml
> +    sources:
```suggestion
    config-opts:
      - '-Dexamples=false'
      - '-Dtests=false'
    sources:
```

2020-11-03 18:18 UTC, Marukesu commented on io.elementary.screenshot.yml
> +        tag: '1.0.0'
```suggestion
        tag: '1.0.1'
```

2020-11-03 18:19 UTC, Marukesu commented
also, if we wanna to update the runtime to 3.38 and the base to juno-20.08 we need to build canberra in the manifest, similar to camera here:
https://github.com/elementary/camera/blob/6e3e8e5751a8f884502242d5b969c53a85b36d5c/io.elementary.camera.yml#L27

2020-11-03 20:17 UTC, danrabbit commented
@Marukesu thanks for catching those!

2020-11-03 20:36 UTC, Marukesu approved these changes

2020-11-03 20:43 UTC, merged