Consistently use 'Capture' verb
elementary/screenshot pull request #196
Opened 2020-11-03 19:07 UTC by cassidyjames

Intends to fix #195. Open to discussion.

2020-11-03 19:28 UTC, danrabbit commented
Hrrmmmm I haven't pulled this yet but my first couple of thoughts are:

Having capture in every label in the UI seems bad. I feel like it's generally not good to be too repetitive, especially when trying to show the differences between options

"Capture screenshot of the whole screen" doesn't seem better than "Screenshot the whole screen"

Perhaps we should lean towards just using "screenshot" as a verb where it makes sense. Our window menu label could be "Screenshot This Window" and that seems pretty clear without being overly verbose 

Reading it back, I also feel like both "Grab pointer" and "Capture pointer" are probably less clear than "Include pointer"

2020-11-03 19:40 UTC, fabiozaramella commented
> Having capture in every label in the UI seems bad. I feel like it's generally not good to be too repetitive, especially when trying to show the differences between options

I agree, it would end up being repetitive.

> Perhaps we should lean towards just using "screenshot" as a verb where it makes sense. Our window menu label could be "Screenshot This Window" and that seems pretty clear without being overly verbose

I think it's better to avoid using nouns as verbs when possible, especially when terms like this are not really translatable into other languages. For example "Grab this Window" is translated in italian as "Cattura questa finestra" whereas "Screenshot this Window" can't be translated properly. I mean, we can keep the same translation of course but my concern is that some other new translators (or in other languages) may translate improperly for example using the slang "Screenshottare" (to take a screenshot) in the italian case.

> Reading it back, I also feel like both "Grab pointer" and "Capture pointer" are probably less clear than "Include pointer"

I also agree that "Include pointer" is better.

2020-11-04 19:12 UTC, cassidyjames commented
Yeah being repetitive is a problem. But before we were using at least 3 different verbs, so I think we should align on what verb we use in general for taking screenshots and use that consistently. At the same time, we should work to reduce repetitiveness.

2020-11-04 19:19 UTC, cassidyjames commented
Okay I like this more. It's more concise in general and should address what you both brought up. Now I guess, do we like "Capture" or "Take" better? Regarding .desktop action names, see: https://github.com/elementary/applications-menu/issues/277 as I think that will also make this work better, as with other apps.

2020-11-04 20:54 UTC, fabiozaramella approved these changes
Not in the UX team and I still want to hear from Daniel, but is approval from me.

2020-11-18 02:04 UTC, danrabbit requested changes
Left a couple inline comments.

Have you tested that actions still appear when searching for "Screenshot" even if their text doesn't contain that word?

2020-11-18 02:04 UTC, danrabbit commented on src/ScreenshotWindow.vala
> +        var take_btn = new Gtk.Button.with_label (_("Capture Screenshot"));
I think I like "take" more here tbh. I'm not sure why but it feels more natural to me for some reason

2020-11-18 02:04 UTC, danrabbit commented on data/screenshot.desktop.in
> +Name=Select Area to Capture
Hm, should this instead be
```suggestion
Name=Capture a Selected Area
```

2020-12-22 19:12 UTC, danrabbit commented
This hasn't moved in a month so I'm gonna kick it to a draft

2020-12-23 07:05 UTC, cassidyjames commented on src/ScreenshotWindow.vala
> +        var take_btn = new Gtk.Button.with_label (_("Capture Screenshot"));
```suggestion
        var take_btn = new Gtk.Button.with_label (_("Take Screenshot"));
```

2020-12-23 07:09 UTC, cassidyjames commented
@danrabbit couple of comments addressed.

> Have you tested that actions still appear when searching for "Screenshot" even if their text doesn't contain that word?

As mentioned in https://github.com/elementary/screenshot/issues/196#issuecomment-721924434:

>Regarding .desktop action names, see: https://github.com/elementary/applications-menu/issues/277 as I think that will also make this work better, as with other apps.

Do you consider that a blocker?

2023-02-09 22:20 UTC, closed without merging